### ISSUE TITLE
Not x64

### ISSUE THREAD

**Issue by wreiske** [ArmenAg/Improvisation#2]
Any reason why you have "prefer 32bit" enabled in the build options? 

I set the architecture to 64bit and built fine, it's now processing much faster too. Just curious if there was a reason why you were only building for 32 bit.

**Comment by ArmenAg** [comment]
Hello William,

That was something that I overlooked. The prefer 32Bit option is the default option in visual studio, but you’re completely right. I need to migrate it to 64Bit.

Thank you,

Armen A
